# params.yaml

# custom site params
author: Ideas on Stage
email: info@ideasonstage.com
favicon: /img/ios_favicon.ico

# CSS
css:
    customfonts: [ "https://cloud.typography.com/6201816/7621392/css/fonts.css" ]

# responsive images sizes (for generation of srcset)
images:
    landscape:
        - scale: 2400
          size: "2400px"
        - scale: 1200
          size: "(1200px > width >= 720px) 1200px"
        - scale: 720
          size: "(720px > width) 720px"
    portrait:
        - scale: 1600
          size: "1600px"
        - scale: 800
          size: "(1600px > width >= 800px) 800px"
        - scale: 480
          size: "(480px > width) 480px"
    quality: 70

# ---------------------
# navigation
navigation:
    brand: "Ideas on Stage"
    brand_logo: "/img/ideas-on-stage.svg"
    brand_logo_height: "48px"
    brand_logo_offset: "2px"
    brand_ball: "/img/ideas-on-stage-ball.svg"
    languageicon: "/img/globe.svg"
    languageiconhover: "/img/globe_hover.svg"
    burger_height: "16px"
    burger_width: "16px"

# ---------------------
# schema organization
organization:
    logo: /img/ideas-on-stage.svg
    name: Ideas on Stage
    sameas:
        - https://www.linkedin.com/company/ideas-on-stage/
        - https://www.youtube.com/user/IdeasOnStage
        - https://www.pierremorsa.com/ideas-on-stage/