# !!! TEST A REDIRECTION AFTER MODIFYING THE FILE TO BE SURE IT'S CORRECT
# 1 mistake and the whole file may be ignored by Netlify

# --------
# TOP LEVEL DOMAIN NAMES REDIRECTS

# PERMANENT redirect .es .fr sites to /es/ /fr/
[[redirects]]
	from	= "https://www.ideasonstage.es/*"
	to		= "https://www.ideasonstage.com/es/:splat"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.fr/*"
	to		= "https://www.ideasonstage.com/fr/:splat"
	status	= 301
	force	= true



# --------
# SUBDOMAIN NAMES REDIRECTS

# redirect bienvenue
[[redirects]]
	from	= "https://bienvenue.ideasonstage.com/*"
	to		= "https://www.ideasonstage.com/fr/formations-prise-de-parole-en-public/comment-vous-preparer-pour-nos-formations/"
	status	= 301
	force	= true
	
# redirect catalogue
[[redirects]]
	from	= "https://catalogue.ideasonstage.com/*"
	to		= "https://www.ideasonstage.com/guides/ideasonstage-catalogue-en.pdf"
	status	= 301
	force	= true	
[[redirects]]
	from	= "https://catalogue.ideasonstage.com/fr/*"
	to		= "https://www.ideasonstage.com/guides/ideasonstage-catalogue-fr.pdf"
	status	= 301
	force	= true

# redirect supports de formation standard
[[redirects]]
	from	= "https://formation.ideasonstage.com/*"
	to		= "https://www.ideasonstage.com/fr/formations-prise-de-parole-en-public/supports/:splat"
	status	= 301
	force	= true

# redirect questionnaire pr√©-formation
[[redirects]]
	from	= "https://preformation.ideasonstage.com/*"
	to		= "https://www.survio.com/survey/d/D3T4A8Q9X1D4U3M7S"
	status	= 301
	force	= true

# redirect revolution
[[redirects]]
	from	= "https://revolution.ideasonstage.com/*"
	to		= "https://www.ideasonstage.com/revolution/"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://revolution.ideasonstage.com/fr/*"
	to		= "https://www.ideasonstage.com/fr/revolution/"
	status	= 301
	force	= true

# redirect questionnaire post-formation
[[redirects]]
	from	= "https://satisfaction.ideasonstage.com/*"
	to		= "https://www.survio.com/survey/d/K5J7A9O3T5J3I0G8I"
	status	= 301
	force	= true

# redirect questionnaire satisfaction partnenaires
[[redirects]]
	from	= "https://partenaires.ideasonstage.com/*"
	to		= "https://www.survio.com/survey/d/K5J7A9O3T5J3I0G8I"
	status	= 301
	force	= true



# --------
# EXTERNAL URL REDIRECTS

# redirect in (linkedin)
[[redirects]]
	from	= "https://www.ideasonstage.com/in/"
	to		= "https://www.linkedin.com/company/ideas-on-stage/"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://in.ideasonstage.com/*"
	to		= "https://www.linkedin.com/company/ideas-on-stage/"
	status	= 301
	force	= true

# UK Andrea's stuff redirects
[[redirects]]
	from	= "https://www.ideasonstage.com/score/"
	to		= "https://presentationscorecard.scoreapp.com/"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.com/uk/score/"
	to		= "https://presentationscorecard.scoreapp.com/"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.com/uk/masterclass/"
	to		= "http://ideasonstageuk.eventbrite.com/"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.com/uk/bpr-pdf/"
	to		= "https://mailchi.mp/7b5193d808cb/bpr-pdf"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.com/uk/value-bundle/"
	to		= "https://mailchi.mp/5975bea9212e/value-bundle/"
	status	= 301
	force	= true



# --------
# TEMPORARY CANONICAL FIX REDIRECTS

# Redirect for ATR pdf
[[redirects]]
	from	= "https://www.ideasonstage.com/services/communication-consulting/audience-transformation-roadmap/ATR_template_Ideas_on_Stage.pdf"
	to		= "https://www.ideasonstage.com/files/ATR_template_Ideas_on_Stage.pdf"
	status	= 301
	force	= true

# 2024-07-09
[[redirects]]
	from	= "https://www.ideasonstage.com/fr/references/*"
	to		= "https://www.ideasonstage.com/fr/apropos/references/:splat"
	status	= 301
	force	= true

# 2024-09-02 revolution redirect
[[redirects]]
	from	= "https://www.ideasonstage.com/revolution/*"
	to		= "https://www.ideasonstage.com/resources/revolution/:splat"
	status	= 301
	force	= true
[[redirects]]
	from	= "https://www.ideasonstage.com/fr/revolution/*"
	to		= "https://www.ideasonstage.com/fr/ressources/revolution/:splat"
	status	= 301
	force	= true



# --------
# 404 REDIRECTS

[[redirects]]
	from	= "/es/*"
	to		= "/es/404/"
	status	= 404
[[redirects]]
	from	= "/fr/*"
	to		= "/fr/404/"
	status	= 404
[[redirects]]
	from	= "/*"
	to		= "/404/"
	status	= 404
